[agent]
omit_hostname = true

[[inputs.mqtt_consumer]]
servers = ["tcp://localhost:1883"]
topics = [ "fridges/sensor_data" ]
username = "telegraf"
password = "${TELEGRAF_MOSQUITTO_PW}"
data_format = "json_v2"
topic_tag = ""

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "fridge"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"

[[outputs.influxdb_v2]]
urls = ["http://localhost:8086"]
token = "${TELEGRAF_INFLUX_TOKEN}"
organization = "lasolarpunk"  
bucket = "freefridges"

